### ISSUE TITLE
Added a 'Supported by' section on webpage

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/dev-ogc-org-sprint-landing-22#3]
Please add a 'Supported by' section on the web page.

Please add the logos shown at https://github.com/opengeospatial/developer-events/wiki/October-2023-Open-Standards-Code-Sprint#supported-by

**Comment by ghobona** [comment]
@doublebyte1 I added the section manually to these HTML files.

master branch, https://github.com/opengeospatial/dev-ogc-org-sprint-landing-22/commit/984788c926a4e6afe67b528f9bae10002ecff822

gh-pages branch, https://github.com/opengeospatial/dev-ogc-org-sprint-landing-22/commit/e399ff998699eca6eca2bcd3e22270914626dd81

gh-pages-v2 branch on developer-website repo, https://github.com/opengeospatial/developer-website/commit/806c5fee489dbc550dc0e401f521899456d1f83f

The edits will need to be made on the pug scripts as well.

**Comment by doublebyte1** [comment]
Added here: https://github.com/opengeospatial/dev-ogc-org-sprint-landing-22/commit/da8d094b2680803e9bb8aa6d3a1a086563e5ebeb

Thanks @ghobona ! 👍🏽
