### ISSUE TITLE
Add list of three recommended hotels

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/dev-ogc-org-sprint-landing-22#4]

**Comment by doublebyte1** [comment]
@ghobona do you have any suggestions?

**Comment by doublebyte1** [comment]
- [The Premier Inn](https://www.premierinn.com/gb/en/hotels/england/greater-london/london/london-farringdon-smithfield.html?cid=GLBC_LONSMI) -  14 mins
- [NHow London ](https://www.nhow-hotels.com/en/nhow-london) - 10 mins
- [Marrable's](https://marrableshotel.com/) -  7 mins
